version: '3.3'
services:
  client:
    image: student-frontend:latest
    restart: always
    build:
      context: ./frontend
    ports:
      - '3000:3000'
  server:
    image: maven:3.8.3-openjdk-17
    volumes:
      - ./backend:/code
    working_dir: /code/
    command: mvn spring-boot:run
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: 'db'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'student_management'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: